[TALK]
== Zimbra Talk V2
Zimbra Talk V2 is the newest addition to the Zimbra product line-up. Zimbra Talk V2 will be available in version 8.8.8 onwards.
This is enterprise-level messaging and videoconferencing built inside the Zimbra web client. It includes one-on-one and group messaging and videoconferencing, along with full screen and file sharing capabilities.

Zimbra Talk V2 inherits some of the features from the previous Zimbra Chat, but the vast majority of the features are new. Some of the inherited features from Chat are (basic features):

* *1-to-1 text messaging*
* *Buddy List Management*
* *Chat history*
* *Emojis*
* *Status or presence management*
* *User preferences*

Zimbra Talk V2 provides advanced features. These features are:

* *Message Delivery and Read Awareness.* Check marks show delivery or read status
* *Group Messaging.* Secure and private messaging for small groups (up to 5 people)
* *Videoconferencing.* WebRTC based video, out-of-the-box without any plug-in
* *Corporate Communications.* Spaces and Channels for private or organization-wide communications
* *File Sharing*
* *Screen Sharing*

Beginning in Zimbra Collaboration Network Edition 8.8.8, the Zimbra Talk Zimlet will provide the basic chat features, these features will be available for all of your users. In order to enable the advanced chat and videoconferencing features per user, a purcharse of Zimbra Talk V2 license is needed.

Zimbra Talk V2 has two user interfaces: *Chat Panel and Zimbra Talk tab*.

The *Chat Panel* is available to all users - basic and advanced - for text messaging. Advanced users will have the additional options of videoconferencing and file sharing in the panel.

The *Zimbra Talk* tab is only available for advanced Zimbra Talk users. This tab offers all of the corporate instant messaging features such as Spaces and Channels. 

Advanced Zimbra Talk users will have three options to interact with other users: Groups, Spaces, and Channel.

*Groups*

Groups are the basic way of communicating with multiple people at the same time (up to 5 total). Those are non-persistent entities that are not tied to any specific space: any user can create a group inviting people from their Buddy List and any group member can invite more people in the same way. When all users leave a group, the group itself ceases to exist.

*Groups Features* 

* A user in a Group can add more users to the Group itself up to the allowed limit.

* A user in a Group can chat with all of the others. Messages sent in a Group are viewed by all members of that Group.

* A user in a Group can send files to all of the others. Files sent in a Group are available to all members of that Group.

* A user in a Group can start a videoconference with all of the others. Group videoconferences can be joined at any time by all members of the Group.
